name: Test macOS

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
    - run: npm cache verify 
    - run: npm login
    - run: npm install 
    - run: npm test
      env:
        CI: true
